apiVersion: v1
kind: Service
metadata:
  name: time-app-service
spec:
  selector:
    app.kubernetes.io/name: gorilla-logic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer